apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
stringData:
  DB_HOST: capstone-db.cgdmsqcsym14.us-east-1.rds.amazonaws.com
  DB_USER: dbadmin
  DB_PASSWORD: "&kk#7xFJ6KzK8-KUPiru"
  DB_NAME: executedb
